// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nmkjmdcdaeigbepvuaqj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ta2ptZGNkYWVpZ2JlcHZ1YXFqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyMTY1NTIsImV4cCI6MjA1MTc5MjU1Mn0.HBjnDyYjLICw42B9EcT78Tcos3_a_R1DNN3FmyePsgc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);